version: '3'
services:
  opensearch: 
    image: opensearchproject/opensearch:2.12.0
    container_name: opensearch-node1
    environment:
      - cluster.name=test 
      - node.name=opensearch-node1 
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - network.publish_host=127.0.0.1
      - logger.org.opensearchsearch=warn
      - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g" 
      - plugins.security.nodes_dn_dynamic_config_enabled=true
      - plugins.security.unsupported.restapi.allow_securityconfig_modification=true
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=vLPeJYa8.3RqtZCcAK6jNz
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - 9200:9200
    networks:
      - opensearch-net
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.12.0
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch-node1:9200"]'
      OPENSEARCH_USERNAME: admin
      OPENSEARCH_PASSWORD: vLPeJYa8.3RqtZCcAK6jNz
    networks:
      - opensearch-net

networks:
  opensearch-net: